apiVersion: v1
kind: Pod
metadata:
  name: pod-api
spec:
  containers:
    - name: simple-api
      image: leandrochp/simple-node-api
      env:
        - name: PORT
          value: "8080"
      ports:
        - containerPort: 8080
