apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pi
              image: perl
              args:
                - perl
                - "-Mbignum=bpi"
                - "-wle"
                - print bpi(2000)
          restartPolicy: OnFailure
