apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    role: database
spec:
  containers:
    - name: mongo-container
      image: mongo #kubectl exec -it mongo-pod -- mongosh
      ports:
        - containerPort: 27017
          name: mongo-port
      volumeMounts:
        - mountPath: /data/db
          name: mongo-volume
  volumes:
    - name: mongo-volume
      persistentVolumeClaim:
        claimName: mongo-claim
